README.md
org.rncbc.qtractor.json
qtractor.sh

Issue #7 - Fix VST and VST3 path

---

org.rncbc.qtractor.json

A Spring'23 Release (v0.9.34)

---

org.rncbc.qtractor.json

Update to vst3sdk v3.7.8_build_34

---

org.rncbc.qtractor.json

Update rubberband v3.3.0

---

org.rncbc.qtractor.json

An End-of-Summer'23 Release (v0.9.35)

---

org.rncbc.qtractor.json

An Autumn'23 Release (v0.9.36)

---

aubio.json
org.rncbc.qtractor.json
rubberband.pc

An End-of-Autumn'23 Release (v0.9.37)

---

org.rncbc.qtractor.json

An End-of-Year'23 Release (v0.9.38)

---

org.rncbc.qtractor.json

A Spring'24 Release Candidate (aka. v1.0.0-rc1)

---

org.rncbc.qtractor.json

An Unthinkable Release (aka. v1.0.0)

---

org.rncbc.qtractor.json

A Summer'24 Release (v1.1.0)

---

org.rncbc.qtractor.json

A Summer'24 Hotfix Release (v1.1.1)

---

org.rncbc.qtractor.json

Updated org.rncbc.qtractor.json

A Mid-Summer'24 Release (v1.2.0)

---

aubio.json

Doing some infra related testing, please ignore.

Test aubio.org downloads

---

org.rncbc.qtractor.json

Updated org.rncbc.qtractor.json;
Updated shared-modules.

An End-of-Year'24 Release (v1.5.0)

---

org.rncbc.qtractor.json
patches/aubio-python.patch

Updated org.rncbc.qtractor.json

An(other) End-of-Year'24 Release (v1.5.1)

---

org.rncbc.qtractor.json

- Updated org.rncbc.qtractor.json;
- Updated shared-modules.

A New-Year'25 Release (v1.5.2)

---

org.rncbc.qtractor.json

Updated org.rncbc.qtractor.json;
Updated shared-modules.

A Mid-Winter'25 Release (v1.5.3)

---

org.rncbc.qtractor.json

Updated org.rncbc.qtractor.json;
Updated shared-modules.

An Early Spring Release (v1.5.4)

---

org.rncbc.qtractor.json

updated org.rncbc.qtractor.json
updated shared-modules

A Summer'25 Release (v1.5.7)

---

org.rncbc.qtractor.json

- updated org.rncbc.qtractor.json;
- updated shared-modules.

A Late Summer'25 Release (v1.5.8)
